### PR TITLE
[6.0] Specify attributes inside `#if` before any unconditional attributes

### PR DESCRIPTION
**Pull request by ahoppen**
* **Explanation**: Specifying the `#if` conditionalized attribute after an unconditional attribute results in a compilation error when using a Swift 5.7 compiler. Reversing the order makes swift-syntax build with a Swift 5.7 compiler.
* **Scope**: Fixes a compilation error when building swift-syntax with a 5.7 compiler
* **Risk**: Very low, just flips two declaration attributes
* **Testing**: Tested that that the package builds with 5.7 with this change
* **Issue**: rdar://124979624, #2546 
* **Reviewer**:  @bnbarham on https://github.com/apple/swift-syntax/pull/2548

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by bnbarham — APPROVED** [review]
