### ISSUE TITLE
Crash when parsing initializer with unavailable attribute

### ISSUE THREAD

**Issue by jpsim** [apple/swift-syntax#1025]
### Issue Kind

Parser Crash

### Source Code

```swift
struct Math {
  public static let pi = 3.14
  @available(*, unavailable) init() {}
}
```

### Description

Tested with 79c8e55d2773c249342ae21abd8a2e0df88ebc5f (`main` as of today):

```swift
let source = """
  struct Math {
    public static let pi = 3.14
    @available(*, unavailable) init() {}
  }
  """
dump(Parser.parse(source: source))
```

Results in this fatal error unwrapping an optional:

> SwiftSyntax/SyntaxNodes.swift:24664: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by jpsim** [comment]
Seems to have been introduced in d3471fdb4b49c9f91343b587af8f531f8bbb4a4c

**Comment by ahoppen** [comment]
rdar://101589498

**Comment by ahoppen** [comment]
Ah, we are now taking advantage of the `node_choices` constraints with the commit you mentioned above but were aren’t actually enforcing that these constraints are upheld in the parser, causing the crash. I’m working on resolving this in https://github.com/apple/swift-syntax/pull/1032.

**Comment by jpsim** [comment]
Glad to see you're on top of it.

Should d3471fdb4b49c9f91343b587af8f531f8bbb4a4c be reverted if it's preventing `main` from parsing valid syntax?

Especially if the fix from #1032 isn't going to be ready quickly?

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/1034 should fix the issue and I hope to land it today or at least tomorrow. I hope that’s sufficient.

**Comment by jpsim** [comment]
Thanks for the update, that PR looks good on my end, and I'm not in a big rush to update on `main`, but the pace of development and breaking changes is fast enough that I'd rather not get too far behind.

**Comment by jpsim** [comment]
There's still a `SIGTRAP` crash with ecd2ba9c7edc2e82904a3e32790ee0a1867059f7 compared to 4ad75a85f5f14caecdd6cdb41c4c9a090ce82340 though when parsing source files from the the `apple/swift` repo. I'll dig further into that to narrow it down.

**Comment by jpsim** [comment]
Here's the file that's crashing: https://github.com/apple/swift/blob/main/stdlib/public/Distributed/DistributedActor.swift

**Comment by jpsim** [comment]
With ecd2ba9c7edc2e82904a3e32790ee0a1867059f7:

```swift
let file = URL(fileURLWithPath: "stdlib/public/Distributed/DistributedActor.swift")
let source = try! String(contentsOf: file)
dump(Parser.parse(source: source))
```

> SwiftSyntax/SyntaxCollections.swift:7144: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by ahoppen** [comment]
Ah, I forgot to do the same checks for syntax collections. Should be in https://github.com/apple/swift-syntax/pull/1034 now.

**Comment by jpsim** [comment]
Ok, #1034 looks good on my end now.
